SELECT
  X.BJ36NO08, --ATM机设备编号
  SUM(NBR_TOTAL_D) NBR_TOTAL, ----该ATM机交易总笔数，汇总到月
  SUM(AMT_QX_D) AMT_QX, --该ATM机取现交易总金额，汇总到
  SUM(NBR_QX_D) NBR_QX, --该ATM机取现交易总笔数，汇总到
  SUM(AMT_CX_D) AMT_CX, --该ATM机存现交易总金额，汇总到
  SUM(NBR_CX_D) NBR_CX, --该ATM机存现交易总笔数，汇总到 
  SUM(AMT_ZZ_D) AMT_ZZ, --该ATM机转账交易总金额，汇总到
  SUM(NBR_ZZ_D) NBR_ZZ, --该ATM机转账交易总笔数，汇总到
  SUM(AMT_QX_BDT_D) AMT_QX_BDT, --该ATM机本代他取现交易总金额，汇总到
  SUM(NBR_QX_BDT_D) NBR_QX_BDT, --该ATM机本代他取现交易总笔数，汇总到
  SUM(AMT_ZZ_BDT_D) AMT_ZZ_BDT, --该ATM机本代他转账交易总金额，汇总到
  SUM(NBR_ZZ_BDT_D) NBR_ZZ_BDT, --该ATM机本代他转账交易总笔数，汇总到
  SUM(CASE WHEN NBR_TOTAL_D>NBR_TYPE THEN 1 ELSE 0 END) DAYS_TOTALAVG, --该ATM机交易笔数大于同机型当月每台每天交易笔数的天数，即大于同机型平均水平的天数
  COUNT(BJ01DATE) DAYS_WORK, --该ATM机当月有交易天数
  SUM(CASE WHEN NBR_TOTAL_D>NBR_AVG_SELF THEN 1 ELSE 0 END) DAYS_SELFAVG --该ATM机交易笔数大于自身当月每天交易笔数的天数
FROM
(
  SELECT
    A.BJ36NO08, --ATM机设备编号
    BJ01DATE, --交易日期
    ATM_TYPE, --ATM机设备机型，1一体机，2取款机
    COUNT(1) NBR_TOTAL_D, --该ATM机交易总笔数，汇总到天
    SUM(CASE WHEN B.TXTPINVT='3' THEN B.TAMTAMT END) AS AMT_QX_D, --该ATM机取现交易总金额，汇总到天
    COUNT(CASE WHEN B.TXTPINVT='3' THEN B.TAMTAMT END) AS NBR_QX_D, --该ATM机取现交易总笔数，汇总到天
    SUM(CASE WHEN B.TXTPINVT='4' THEN B.TAMTAMT END) AS AMT_CX_D, --该ATM机存现交易总金额，汇总到天
    COUNT(CASE WHEN B.TXTPINVT='4' THEN B.TAMTAMT END) AS NBR_CX_D, --该ATM机存现交易总笔数，汇总到天
    SUM(CASE WHEN A.BJ20FLAG='2' THEN A.BJ16AMT END) AS AMT_ZZ_D, --该ATM机转账交易总金额，汇总到天
    COUNT(CASE WHEN A.BJ20FLAG='2' THEN A.BJ16AMT END) AS NBR_ZZ_D, --该ATM机转账交易总笔数，汇总到天
    SUM(CASE WHEN (B.TXTPINVT='3' AND A.BJ17CDFG='2') THEN A.BJ16AMT END) AS AMT_QX_BDT_D, --该ATM机本代他取现交易总金额，汇总到天
    COUNT(CASE WHEN (B.TXTPINVT='3' AND A.BJ17CDFG='2') THEN A.BJ16AMT END) AS NBR_QX_BDT_D, --该ATM机本代他取现交易总笔数，汇总到天
    SUM(CASE WHEN (A.BJ20FLAG='2' AND A.BJ17CDFG='2') THEN A.BJ16AMT END) AS AMT_ZZ_BDT_D, --该ATM机本代他转账交易总金额，汇总到天
    COUNT(CASE WHEN (A.BJ20FLAG='2' AND A.BJ17CDFG='2') THEN A.BJ16AMT END) AS NBR_ZZ_BDT_D --该ATM机本代他转账交易总笔数，汇总到天
  FROM 
  (
    SELECT * FROM SDI_F_CORE_BDFMHQBJ
    WHERE SUBSTR(BJ01DATE,1,6)='201611'
      AND BJ19JYLX='1' --正常交易
      AND TRIM(RCSTRS1B)='' --记录状态未删除
      AND END_DATE='99990101'   
    AND BJ36NO08 IN 
    (
      SELECT DISTINCT ATMNNO08 FROM SDI_F_CORE_BWFMATMB
      WHERE TRIM(RCSTRS1B)='' AND END_DATE='99990101'
          )
  ) A
  LEFT JOIN 
  (
    SELECT * FROM SDI_F_CORE_BWFMATMD 
    WHERE SUBSTR(TXDTDATE,1,6)='201611'
      AND TRIM(RCSTRS1B)=''
      AND END_DATE='99990101'
   ) B ON A.BJ01DATE = B.TXDTDATE AND A.BJ06TXSN = B.LPTNTXSN --以交易日期和流水号关联
   LEFT JOIN SDI_M_DATA_INPUT_ATM_BASE_INFO C ON C.ATM_NO = A.BJ36NO08
  GROUP BY A.BJ36NO08, BJ01DATE, ATM_TYPE
) X
LEFT JOIN
(
  SELECT ATM_TYPE, COUNT(1)/COUNT(DISTINCT BJ36NO08)/30 NBR_TYPE --同一机型ATM机平均每台每天交易笔数
    FROM 
  (
    SELECT * FROM SDI_F_CORE_BDFMHQBJ
    WHERE SUBSTR(BJ01DATE,1,6)='201611'
      AND BJ19JYLX='1' 
      AND TRIM(RCSTRS1B)=''
      AND END_DATE='99990101'   
    AND BJ36NO08 IN 
    (
      SELECT DISTINCT ATMNNO08 FROM SDI_F_CORE_BWFMATMB
      WHERE TRIM(RCSTRS1B)='' AND END_DATE='99990101'
          )
  ) A
   LEFT JOIN SDI_M_DATA_INPUT_ATM_BASE_INFO B ON B.ATM_NO = A.BJ36NO08
   GROUP BY ATM_TYPE
) Y ON Y.ATM_TYPE = X.ATM_TYPE
LEFT JOIN
(
  SELECT BJ36NO08, COUNT(1)/30 NBR_AVG_SELF --同一ATM机平均每台每天交易笔数
    FROM 
  (
    SELECT * FROM SDI_F_CORE_BDFMHQBJ
    WHERE SUBSTR(BJ01DATE,1,6)='201611'
      AND BJ19JYLX='1' 
      AND TRIM(RCSTRS1B)=''
      AND END_DATE='99990101'   
    AND BJ36NO08 IN 
    (
      SELECT DISTINCT ATMNNO08 FROM SDI_F_CORE_BWFMATMB
      WHERE TRIM(RCSTRS1B)='' AND END_DATE='99990101'
          )
    )
    GROUP BY BJ36NO08
) Z ON Z.BJ36NO08 = X.BJ36NO08
GROUP BY X.BJ36NO08

